### PR TITLE
fix: get nonce in `getWalletNonce`

### PR DESCRIPTION
**Pull request by dated**
The nonce lookup is currently broken, always returning `0`.

### CODE REVIEW

**Comment by sebastijankuzner** [comment]
It doesn't seem to be broken. Mainsail API returns data without data property. Example:

Code:
```
        const response = await http.get(`${getApiServerUrl(peer)}/api/wallets/${publicKey}`);
        console.log(response.data);
```

Response:
```{
  address: 'DNvqMC1YBF76AoT1emyqVGHyfwNw31RCws',
  publicKey: '03f25455408f9a7e6c6a056b121e68fbda98f3511d22e9ef27b0ebaf1ef9e4eabc',
  balance: '235849026603773',
  nonce: '6',
  attributes: {
    vote: '03f25455408f9a7e6c6a056b121e68fbda98f3511d22e9ef27b0ebaf1ef9e4eabc',
    nonce: '6',
    balance: '235849026603773',
    username: 'genesis_1',
    publicKey: '03f25455408f9a7e6c6a056b121e68fbda98f3511d22e9ef27b0ebaf1ef9e4eabc',
    validatorRank: 49,
    validatorApproval: 1.89,
    validatorLastBlock: {
      id: 'fbcf6cb37ece72593a963e5b6d00b4cc3b8e96a6bdc226a5a3057d353433a53d',
      height: 492,
      timestamp: 1710150064644
    },
    validatorPublicKey: '8a0836e15156b95cab8fbfb756cd2a5ce27909cc23752691b991831dfcd3c4a15be1e7b883566d0d5c4f068adcc1c588',
    validatorForgedFees: '0',
    validatorForgedTotal: '0',
    validatorVoteBalance: '235849026603773',
    validatorForgedRewards: '0',
    validatorProducedBlocks: 10
  },
  updated_at: '508'
}```

**Comment by dated** [comment]
Strange, i have the API Server installed locally, and that returns everything wrapped in `data` property. I'll see if I can figure out why.

**Comment by dated** [comment]
Oh, found it @sebastijankuzner. I defined a custom `CORE_API_PORT` port, and if i query the node using that port, the data is wrapped. If I query the node with port 4006 (api-development) I get the data as you describe. Where does that port come from? Why is the api reachable through two ports?

**Comment by sebastijankuzner** [comment]
CORE_API_PORT is used by `api-http` package which is usually started as separate `mainsail-api` process. Anyway it returns the data in same format as api-development. 

Mainsail tx tester works with either `api-http` (4003) or `api-development` (4006). And requires api-transaction-pool (4007) for sending transactions. 

Can you check your app.json to see which api-* packages are enabled?

**Comment by dated** [comment]
I've disabled api-development now. I am indeed using the separate mainsail-api process, and that one Most definitely returns a differently structured reaponse on my node.

```
➜  ~ curl http://127.0.0.1:4004/api/wallets/ddated | jq
{
  "data": {
    "address": "DGcG7LZ6pFnnuUufNXzyxCBKwq1ffKLiR2",
    "publicKey": "02dfc9a0684fe0744101b2398e9c86a81b5e46aceffff994ef9189083f01d0bebb",
    "balance": "27560000001",
    "nonce": "7",
    "attributes": {
      "vote": "02dfc9a0684fe0744101b2398e9c86a81b5e46aceffff994ef9189083f01d0bebb",
      "nonce": "7",
      "balance": "27560000001",
      "username": "ddated",
      "publicKey": "02dfc9a0684fe0744101b2398e9c86a81b5e46aceffff994ef9189083f01d0bebb",
      "validatorRank": 1,
      "validatorApproval": 1.89,
      "validatorLastBlock": {
        "id": "7aa90c2b7a0c8858c527d5280584877428ab1b8cd6e15cc2cb659a73424622db",
        "height": 73384,
        "timestamp": 1710159345069
      },
      "validatorPublicKey": "a72bddbac9aa0ca6eab0c8821983b2a0924f421fa1a311e45f654643f092a3bf7217ceef5b5743d118a27521faea65f1",
      "validatorForgedFees": "0",
      "validatorForgedTotal": "0",
      "validatorVoteBalance": "235875916603774",
      "validatorForgedRewards": "0",
      "validatorProducedBlocks": 977
    },
    "updated_at": "73405"
  }
}
```

**Comment by dated** [comment]
Nevermind, i had replaced `toResource` with `respondeWithResource` here:
, since the former does not return the usual Error object...

https://github.com/ArkEcosystem/mainsail/blob/79eafc027e7b9404681da1c75dfd42b10979739f/packages/api-http/source/controllers/wallets.ts#L48

**Pull request closed without merging**
